import fs from 'fs';
import path from 'path';
import { execSync } from 'child_process';

/**
 * Resolve appliance version at boot.
 *
 * Priority:
 *  1. .version file (generated by generate-version.sh during build/update)
 *  2. package.json version + live git SHA
 *  3. APP_VERSION env var
 *  4. "0.0.0+unknown"
 */
function resolveVersion(): string {
  // 1. Try .version file (works in production after build/update)
  for (const candidate of [
    path.join(process.cwd(), '.version'),
    path.join(__dirname, '..', '.version'),
  ]) {
    try {
      const content = fs.readFileSync(candidate, 'utf-8').trim();
      if (content && content.includes('+')) return content;
    } catch { /* not found, try next */ }
  }

  // 2. Try package.json + live git SHA
  try {
    const pkgPath = path.join(process.cwd(), 'package.json');
    const pkg = JSON.parse(fs.readFileSync(pkgPath, 'utf-8'));
    const semver = pkg.version || '0.0.0';
    const sha = execSync('git rev-parse --short HEAD', {
      timeout: 3000,
      stdio: ['ignore', 'pipe', 'ignore'],
    }).toString().trim();
    if (sha) return `${semver}+${sha}`;
  } catch { /* no git, try next */ }

  // 3. Env var
  if (process.env.APP_VERSION) return process.env.APP_VERSION;

  // 4. Fallback
  return '0.0.0+unknown';
}

export const APP_VERSION = resolveVersion();
